apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: mysql-secret
type: Opaque
data:
  mysql-user: eWF3YmFkdQ==
  mysql-user-password: cGFzc3dvcmQ=
  mysql-root-password: cGFzc3dvcmQx
