apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: drupal-deploy
  name: drupal-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: drupal-deploy
    spec:
      containers:
      - image: drupal
        name: drupal
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-user
          name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-user-password
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: database_url

---
apiVersion: v1
kind: Service
metadata:
  name: drupal-svc
spec:
  selector:
    app: drupal-deploy
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 32000
